In [1]:
import re
from bs4 import BeautifulSoup
import requests
import pandas as pd

def get_price(self, id):
    return id and re.compile("price_").search(id)

def get_game_price(region, console, game):
    if region != "NTSC":
        url = "https://www.pricecharting.com/game/"+ region + "-" + console + "/" + game.replace(" ", "-").replace("°","").lower()
    else:
        url = "https://www.pricecharting.com/game/"+  console + "/" + game.replace(" ", "-").replace("°","").lower()

    r = requests.get(url)

    df = pd.DataFrame()
    price_list = []


    soup = BeautifulSoup(r.content, 'html.parser')
    eles  = soup.find_all("span", class_="price js-price")

    for price in eles:
        try:
            price_list.append(float(re.findall('(?:[\$\€]{1}[,\d]+.?\d*)',price.string)[0].replace("$","").replace(",","")))
        except:
            price_list.append("No Price Available")

    df['prices'] = price_list[:6]

    df_fin = df.T
    df_fin.columns = ["loose_price", "complete_price", "sealed_price","graded_price", "box_price", "manual_price"]
    
    df_fin["game"] = game
    return df_fin
    print(game)

In [6]:
region = "NTSC" # "NTSC" for NTSC, "JP" for Japan, "PAL" for PAL
console = "Gamecube"
game= "Pokemon BOX"

get_game_price(region, console ,game)

,loose_price,complete_price,sealed_price,graded_price,box_price,manual_price,game
prices,1221.15,1753.75,5086.0,5595.0,1376.0,459.99,Pokemon BOX

In [7]:
region = "PAL" # "NTSC" for NTSC, "JP" for Japan, "PAL" for PAL
console = "Gamecube"
game= "TMNT"

get_game_price(region, console ,game)

,loose_price,complete_price,sealed_price,graded_price,box_price,manual_price,game
prices,No Price Available,178.09,No Price Available,No Price Available,No Price Available,No Price Available,TMNT

In [8]:
region = "PAL"
console = "Gamecube"
games = ["TMNT", "Gadget Racers" ]
games_with_prices = pd.DataFrame()

for game in games:
    df = get_game_price(region, console, game)
    games_with_prices = pd.concat([games_with_prices, df])

games_with_prices.head()

,loose_price,complete_price,sealed_price,graded_price,box_price,manual_price,game
prices,No Price Available,178.09,No Price Available,No Price Available,No Price Available,No Price Available,TMNT
prices,329.97,543.29,1521.0,1673.1,217.32,95.25,Gadget Racers